// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto

#include "hello.pb.h"
#include "hello.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace hello {

static const char* HelloWorld_method_names[] = {
  "/hello.HelloWorld/SayHelloWorld",
  "/hello.HelloWorld/HelloFromServer",
};

std::unique_ptr< HelloWorld::Stub> HelloWorld::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HelloWorld::Stub> stub(new HelloWorld::Stub(channel, options));
  return stub;
}

HelloWorld::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHelloWorld_(HelloWorld_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_HelloFromServer_(HelloWorld_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HelloWorld::Stub::SayHelloWorld(::grpc::ClientContext* context, const ::hello::EmptyRequest& request, ::hello::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hello::EmptyRequest, ::hello::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHelloWorld_, context, request, response);
}

void HelloWorld::Stub::async::SayHelloWorld(::grpc::ClientContext* context, const ::hello::EmptyRequest* request, ::hello::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hello::EmptyRequest, ::hello::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHelloWorld_, context, request, response, std::move(f));
}

void HelloWorld::Stub::async::SayHelloWorld(::grpc::ClientContext* context, const ::hello::EmptyRequest* request, ::hello::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHelloWorld_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hello::HelloReply>* HelloWorld::Stub::PrepareAsyncSayHelloWorldRaw(::grpc::ClientContext* context, const ::hello::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hello::HelloReply, ::hello::EmptyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHelloWorld_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hello::HelloReply>* HelloWorld::Stub::AsyncSayHelloWorldRaw(::grpc::ClientContext* context, const ::hello::EmptyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloWorldRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status HelloWorld::Stub::HelloFromServer(::grpc::ClientContext* context, const ::hello::HelloRequest& request, ::hello::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hello::HelloRequest, ::hello::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_HelloFromServer_, context, request, response);
}

void HelloWorld::Stub::async::HelloFromServer(::grpc::ClientContext* context, const ::hello::HelloRequest* request, ::hello::HelloReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hello::HelloRequest, ::hello::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HelloFromServer_, context, request, response, std::move(f));
}

void HelloWorld::Stub::async::HelloFromServer(::grpc::ClientContext* context, const ::hello::HelloRequest* request, ::hello::HelloReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_HelloFromServer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hello::HelloReply>* HelloWorld::Stub::PrepareAsyncHelloFromServerRaw(::grpc::ClientContext* context, const ::hello::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hello::HelloReply, ::hello::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_HelloFromServer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hello::HelloReply>* HelloWorld::Stub::AsyncHelloFromServerRaw(::grpc::ClientContext* context, const ::hello::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHelloFromServerRaw(context, request, cq);
  result->StartCall();
  return result;
}

HelloWorld::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HelloWorld_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HelloWorld::Service, ::hello::EmptyRequest, ::hello::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HelloWorld::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hello::EmptyRequest* req,
             ::hello::HelloReply* resp) {
               return service->SayHelloWorld(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HelloWorld_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HelloWorld::Service, ::hello::HelloRequest, ::hello::HelloReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HelloWorld::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hello::HelloRequest* req,
             ::hello::HelloReply* resp) {
               return service->HelloFromServer(ctx, req, resp);
             }, this)));
}

HelloWorld::Service::~Service() {
}

::grpc::Status HelloWorld::Service::SayHelloWorld(::grpc::ServerContext* context, const ::hello::EmptyRequest* request, ::hello::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HelloWorld::Service::HelloFromServer(::grpc::ServerContext* context, const ::hello::HelloRequest* request, ::hello::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hello

